import React, { useState, useEffect, useRef } from 'react';
import { Zap, Binary, Cpu, HardDriveDownload, ChevronRight, MoveRight, Send, X, Github, Twitter, BookOpen, Linkedin, Book, Flame, Atom } from 'lucide-react';
import NebulaBackground from './NebulaBackground';

interface LandingPageProps {
    onLogin: () => void;
    onGetStarted: () => void;
    onShowAbout?: () => void;
    onShowTerms?: () => void;
    onShowPrivacy?: () => void;
}

const DEMO_BOOKS = [
    {
        id: 'street',
        input: 'Stop Overthinking & Take Action',
        title: '"Burn the Boat: No More \'Someday\' Shit"',
        shortTitle: 'Burn the Boat',
        subtitle: "No More 'Someday' Shit",
        desc: 'A raw, aggressive take on crushing debt and stacking assets. Generated by Street Mode AI.',
        mode: 'Street Mode',
        engineDesc: 'High-energy, direct, and action-oriented. Perfect for motivation and rapid consumption.',
        words: '19,914',
        chapters: '10',
        url: 'https://cdn.jsdelivr.net/gh/tanmay-kalbande/pustakam-cdn@main/demo-books/Burn_The_Boat_No_More_Someday_Shit.pdf',
        gradient: 'from-cyan-900/40 to-blue-900/40',
        chapterList: ['Burn the Boat', 'Overthinking is Cancer', 'Fear as a Compass', 'The Cost of Delay']
    },
    {
        id: 'stellar',
        input: 'Personal Finance for Young Adults',
        title: '"Architecting Wealth: A Scientific Framework for Financial Growth"',
        shortTitle: 'Wealth Design',
        subtitle: 'Foundations & Mastery',
        desc: 'A structured, formal guide to financial systems and long-term equity. Generated by Stellar Mode AI.',
        mode: 'Stellar Mode',
        engineDesc: 'Academic, thorough, and highly structured. Ideal for complex topics and deep learning.',
        words: '24,152',
        chapters: '12',
        url: 'https://cdn.jsdelivr.net/gh/tanmay-kalbande/pustakam-cdn@main/demo-books/Foundations_Of_Personal_Finance.pdf',
        gradient: 'from-purple-900/40 to-indigo-900/40',
        chapterList: ['The Hidden Tax', 'Compound Mastery', 'Asset Allocation', 'The Wealth Flywheel']
    }
];

const LandingPage = ({ onLogin, onGetStarted, onShowAbout, onShowTerms, onShowPrivacy }: LandingPageProps) => {
    const [activeTab, setActiveTab] = useState<'home' | 'street' | 'stellar' | 'demo' | 'process' | 'features'>('home');
    const [showPromo, setShowPromo] = useState(true);
    const [activeDemoIdx, setActiveDemoIdx] = useState(0);
    const activeBook = DEMO_BOOKS[activeDemoIdx];

    useEffect(() => {
        const promoDismissed = localStorage.getItem('promo_dismissed');
        if (promoDismissed) {
            setShowPromo(false);
        }
    }, []);

    const handleDismissPromo = () => {
        setShowPromo(false);
        localStorage.setItem('promo_dismissed', 'true');
    };

    const renderContent = () => {
        switch (activeTab) {
            case 'street':
                return (
                    <div className="flex flex-col items-center justify-center h-full text-center px-4 animate-in fade-in zoom-in duration-500 w-full max-w-7xl mx-auto">
                        <div className="w-16 h-16 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(6,182,212,0.15)] animate-pulse">
                            <Flame className="w-8 h-8 text-cyan-400 drop-shadow-[0_0_10px_rgba(6,182,212,0.5)]" strokeWidth={1.5} />
                        </div>
                        <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-white mb-4">
                            Street Mode
                        </h1>
                        <p className="text-xl md:text-2xl text-cyan-400 font-medium tracking-wide mb-6">Action Oriented • Raw • Direct</p>

                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-left max-w-5xl w-full mb-10">
                            {[
                                { title: 'No-BS Tone', desc: 'Cuts through the noise with raw, aggressive, and direct language.' },
                                { title: 'Execution Focused', desc: 'Prioritizes actionable steps and "how-to" advice over theory.' },
                                { title: 'High Energy', desc: 'Designed to motivate and push you into immediate action.' }
                            ].map((item, i) => (
                                <div key={i} className="bg-white/5 border border-white/10 rounded-xl p-6 hover:bg-white/10 transition-colors">
                                    <h3 className="text-cyan-400 font-bold mb-2 uppercase tracking-wide text-xs">{item.title}</h3>
                                    <p className="text-white/60 text-sm leading-relaxed">{item.desc}</p>
                                </div>
                            ))}
                        </div>

                        <button
                            onClick={onGetStarted}
                            className="px-8 py-3 bg-cyan-500/10 hover:bg-cyan-500/20 border border-cyan-500/20 hover:border-cyan-500/40 rounded-full text-sm font-medium tracking-wide text-cyan-400 hover:text-cyan-300 transition-all group flex items-center gap-2"
                        >
                            <span>Start Street Mode</span>
                            <MoveRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                        </button>
                    </div>
                );
            case 'stellar':
                return (
                    <div className="flex flex-col items-center justify-center h-full text-center px-4 animate-in fade-in zoom-in duration-500 w-full max-w-7xl mx-auto">
                        <div className="w-16 h-16 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(168,85,247,0.15)]">
                            <Atom className="w-8 h-8 text-purple-400 drop-shadow-[0_0_10px_rgba(168,85,247,0.5)] animate-[spin_10s_linear_infinite]" strokeWidth={1.5} />
                        </div>
                        <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-white mb-4">
                            Stellar Mode
                        </h1>
                        <p className="text-xl md:text-2xl text-purple-400 font-medium tracking-wide mb-6">Deep Learning • Academic • Structured</p>

                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-left max-w-5xl w-full mb-10">
                            {[
                                { title: 'Academic Structure', desc: 'Organizes content into modules, chapters, and quizzes like a textbook.' },
                                { title: 'Concept Mastery', desc: 'Focuses on building deep mental models and theoretical understanding.' },
                                { title: 'Comprehensive', desc: 'Covers topics thoroughly with examples, history, and context.' }
                            ].map((item, i) => (
                                <div key={i} className="bg-white/5 border border-white/10 rounded-xl p-6 hover:bg-white/10 transition-colors">
                                    <h3 className="text-purple-400 font-bold mb-2 uppercase tracking-wide text-xs">{item.title}</h3>
                                    <p className="text-white/60 text-sm leading-relaxed">{item.desc}</p>
                                </div>
                            ))}
                        </div>

                        <button
                            onClick={onGetStarted}
                            className="px-8 py-3 bg-purple-500/10 hover:bg-purple-500/20 border border-purple-500/20 hover:border-purple-500/40 rounded-full text-sm font-medium tracking-wide text-purple-400 hover:text-purple-300 transition-all group flex items-center gap-2"
                        >
                            <span>Start Stellar Mode</span>
                            <MoveRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                        </button>
                    </div>
                );
            case 'process':
                return (
                    <div className="flex flex-col items-center justify-center h-full text-center px-4 animate-in fade-in zoom-in duration-500 w-full max-w-7xl mx-auto">
                        <div className="text-center mb-8">
                            <span className="text-[10px] tracking-[0.4em] uppercase text-cyan-400 mb-2 block opacity-80">The Process</span>
                            <h2 className="text-3xl md:text-5xl font-medium tracking-tight text-white">Your Learning Journey</h2>
                        </div>

                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6 w-full max-w-6xl">
                            {[
                                { step: '01', title: 'Initialize Vision', desc: 'Seed your core concept into the knowledge engine', icon: Zap, color: 'cyan' },
                                { step: '02', title: 'Neural Mapping', desc: 'Architect the tone, depth and learning logic', icon: Binary, color: 'purple' },
                                { step: '03', title: 'Engine Synthesis', desc: 'AI orchestration begins building your knowledge base', icon: Cpu, color: 'amber' },
                                { step: '04', title: 'Ethereal Export', desc: 'Extract your high-fidelity instant PDF book', icon: HardDriveDownload, color: 'emerald' }
                            ].map((item, idx) => (
                                <div key={idx} className="bg-[#050505]/60 border border-white/10 rounded-[22px] px-6 py-8 flex flex-col items-center justify-center text-center hover:border-white/20 transition-all duration-500 group relative overflow-hidden">
                                    <div className={`absolute top-4 right-4 text-[10px] font-mono text-${item.color}-400/40`}>{item.step}</div>
                                    <div className={`w-12 h-12 rounded-xl bg-${item.color}-500/[0.1] border border-${item.color}-500/20 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-500`}>
                                        <item.icon className={`w-6 h-6 text-${item.color}-400/80`} strokeWidth={1.5} />
                                    </div>
                                    <h3 className="text-white font-medium text-sm mb-2 tracking-widest uppercase opacity-90">{item.title}</h3>
                                    <p className="text-white/30 text-[11px] leading-relaxed">{item.desc}</p>
                                </div>
                            ))}
                        </div>

                        <div className="mt-12 flex items-center gap-4 opacity-40">
                            <div className="h-px w-12 bg-gradient-to-r from-transparent to-white/30" />
                            <span className="text-[9px] uppercase tracking-[0.3em] font-light text-white/60">Secure Neural Channels • TLS 1.3</span>
                            <div className="h-px w-12 bg-gradient-to-l from-transparent to-white/30" />
                        </div>
                    </div>
                );
            case 'demo':
                return (
                    <div className="flex flex-col items-center justify-center h-full px-4 animate-in fade-in zoom-in duration-500 w-full max-w-7xl mx-auto">
                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center w-full">
                            {/* Left Side */}
                            <div className="text-left">
                                <span className={`text-[10px] tracking-[0.4em] uppercase mb-4 block ${activeDemoIdx === 0 ? 'text-cyan-400' : 'text-purple-400'}`}>Live Preview</span>
                                <h2 className="text-4xl lg:text-5xl font-medium tracking-tight text-white mb-4 leading-tight">See Pustakam<br />in Action</h2>
                                <p className="text-white/30 text-sm mb-8 max-w-md leading-relaxed">Experience the raw power of AI-generated books. Switch between modes to see how the engine adapts its output.</p>

                                <div className="bg-[#050505]/80 border border-white/10 rounded-xl p-6 mb-8">
                                    <div className="flex gap-2 mb-6">
                                        {DEMO_BOOKS.map((book, i) => (
                                            <button
                                                key={i}
                                                onClick={() => setActiveDemoIdx(i)}
                                                className={`px-4 py-2 rounded-lg text-[10px] font-bold uppercase tracking-widest transition-all duration-300 flex items-center gap-2 border ${i === activeDemoIdx
                                                    ? 'bg-white/10 border-white/20 text-white'
                                                    : 'bg-transparent border-transparent text-white/30 hover:text-white/60'
                                                    }`}
                                            >
                                                {i === 0 ? <Flame className="w-3 h-3" /> : <Atom className="w-3 h-3" />}
                                                {book.mode}
                                            </button>
                                        ))}
                                    </div>

                                    <div className="space-y-2 mb-4">
                                        <div className="text-[10px] text-white/30 font-mono uppercase tracking-wider">Input Prompt</div>
                                        <div className="text-white/90 text-sm font-medium border-l-2 border-white/20 pl-3 py-1">
                                            "{activeBook.input}"
                                        </div>
                                    </div>

                                    <div className="space-y-2">
                                        <div className="text-[10px] text-white/30 font-mono uppercase tracking-wider">Generated Title</div>
                                        <div className={`text-lg font-bold ${activeDemoIdx === 0 ? 'text-cyan-400' : 'text-purple-400'}`}>
                                            {activeBook.title}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Right Side - Book Card */}
                            <div className="relative group perspective-1000">
                                <div className="relative bg-[#050505]/60 border border-white/10 rounded-2xl p-6 transition-all duration-500 hover:border-white/20 transform hover:rotate-y-2">
                                    <div className="flex items-start gap-5 mb-6">
                                        <div className="relative flex-shrink-0 w-24 h-32 bg-[#0a0a0f] rounded-lg border border-white/10 overflow-hidden shadow-2xl">
                                            <div className={`absolute inset-0 bg-gradient-to-br ${activeBook.gradient}`} />
                                            <div className="absolute inset-0 flex flex-col items-center justify-center p-2 text-center">
                                                <div className="text-[8px] text-white/80 font-bold mb-1">{activeBook.shortTitle}</div>
                                                <div className="w-6 h-6 rounded bg-white/10 flex items-center justify-center">
                                                    {activeDemoIdx === 0 ? <Flame className="w-3 h-3 text-white" /> : <Atom className="w-3 h-3 text-white" />}
                                                </div>
                                            </div>
                                        </div>
                                        <div>
                                            <div className="flex items-center gap-2 mb-2">
                                                <span className="px-2 py-0.5 rounded text-[9px] bg-white/10 text-white/60 uppercase tracking-wider border border-white/5">PDF Ready</span>
                                                <span className="text-white/30 text-[10px]">{activeBook.words} Words</span>
                                            </div>
                                            <p className="text-white/50 text-xs leading-relaxed">{activeBook.desc}</p>
                                        </div>
                                    </div>

                                    <a
                                        href={activeBook.url}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className={`flex items-center justify-center gap-2 w-full py-3 rounded-lg text-xs font-bold uppercase tracking-widest transition-all ${activeDemoIdx === 0
                                            ? 'bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400'
                                            : 'bg-purple-500/10 hover:bg-purple-500/20 text-purple-400'}`}
                                    >
                                        <HardDriveDownload className="w-3 h-3" />
                                        <span>Download Sample PDF</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                );
            case 'features':
                return (
                    <div className="flex flex-col items-center justify-center h-full px-4 animate-in fade-in zoom-in duration-500 w-full max-w-7xl mx-auto">
                        <div className="text-center mb-10">
                            <span className="text-[10px] tracking-[0.4em] uppercase text-emerald-400 mb-2 block opacity-80">Capabilities</span>
                            <h2 className="text-3xl md:text-5xl font-medium tracking-tight text-white">Why Pustakam?</h2>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full max-w-6xl">
                            {[
                                { title: 'Instant Generation', desc: 'Get complete learning guides in seconds. Just describe what you want.', icon: Zap, color: 'cyan' },
                                { title: 'Structured Content', desc: 'Every book includes chapters, modules, quizzes, and progress tracking.', icon: Book, color: 'purple' },
                                { title: 'Learn Anything', desc: 'From programming to philosophy — if you can describe it, Pustakam can teach it.', icon: BookOpen, color: 'emerald' }
                            ].map((item, i) => (
                                <div key={i} className="group relative p-8 rounded-3xl bg-white/[0.02] border border-white/5 hover:border-white/10 transition-all duration-500 hover:bg-white/[0.04] text-center md:text-left">
                                    <div className={`w-12 h-12 rounded-xl bg-${item.color}-500/10 flex items-center justify-center mb-6 border border-${item.color}-500/20 mx-auto md:mx-0 group-hover:scale-110 transition-transform`}>
                                        <item.icon className={`w-6 h-6 text-${item.color}-400`} strokeWidth={1.5} />
                                    </div>
                                    <h3 className="text-lg font-medium mb-3 text-white/90">{item.title}</h3>
                                    <p className="text-white/40 font-light leading-relaxed text-sm">{item.desc}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                );
            case 'home':
            default:
                return (
                    <div className="flex flex-col items-center justify-center h-full text-center px-4 animate-in fade-in zoom-in duration-500">
                        <div className="relative z-10 max-w-4xl mb-8">
                            <h1 className="text-5xl md:text-7xl lg:text-8xl font-bold tracking-tight leading-[1.1] text-white mb-2">
                                Your Infinite
                            </h1>
                            <span className="text-4xl md:text-6xl lg:text-7xl font-bold tracking-tight text-white/40 block">Knowledge Engine</span>
                        </div>

                        <p className="text-white/40 text-sm md:text-base max-w-xl leading-relaxed mb-10">
                            Generate personalized learning guides with AI. Choose your mode, define your topic, and master any subject instantly.
                        </p>

                        <div className="flex flex-col sm:flex-row items-center gap-4">
                            <button
                                onClick={onGetStarted}
                                className="relative z-10 px-8 py-3.5 bg-white/5 hover:bg-white/10 border border-white/10 hover:border-white/20 rounded-full text-sm font-medium tracking-wide text-white/90 hover:text-white transition-all group flex items-center gap-2"
                            >
                                <span>Start Learning Now</span>
                                <MoveRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                            </button>
                            <button
                                onClick={() => setActiveTab('process')}
                                className="px-8 py-3.5 text-sm font-medium tracking-wide text-white/40 hover:text-white transition-colors"
                            >
                                How it Works
                            </button>
                        </div>
                    </div>
                );
        }
    };

    return (
        <div className="h-screen w-screen bg-black text-white selection:bg-white/20 selection:text-white overflow-hidden font-sans flex flex-col relative">
            <NebulaBackground />

            {/* Promo Banner - Fixed absolute */}
            {showPromo && (
                <div className="absolute top-24 right-6 z-50 animate-in slide-in-from-right fade-in duration-500">
                    <div className="flex items-center gap-3 pl-4 pr-10 py-3 bg-cyan-950/40 backdrop-blur-md border border-cyan-500/20 rounded-xl shadow-2xl relative group">
                        <span className="relative flex h-2 w-2">
                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-cyan-400 opacity-75"></span>
                            <span className="relative inline-flex rounded-full h-2 w-2 bg-cyan-500"></span>
                        </span>
                        <div className="flex flex-col">
                            <span className="text-cyan-400 text-xs font-bold tracking-wider uppercase">Limited Offer</span>
                            <span className="text-white text-xs font-medium">1 Year Free Membership</span>
                        </div>
                        <button
                            onClick={handleDismissPromo}
                            className="absolute top-2 right-2 p-1 text-white/20 hover:text-white/80 hover:bg-white/10 rounded-full transition-all"
                        >
                            <X size={12} />
                        </button>
                    </div>
                </div>
            )}


            {/* Header */}
            <header className="fixed top-0 left-0 right-0 z-50 px-6 py-6 flex flex-col md:flex-row items-center justify-between gap-4 pointer-events-none md:pointer-events-auto">
                {/* Logo Area */}
                <div className="flex items-center gap-2 cursor-pointer group pointer-events-auto" onClick={() => setActiveTab('home')}>
                    <img src="/white-logo.png" alt="Pustakam AI Logo" className="w-6 h-6 opacity-90" />
                    <span className="text-white/90 font-semibold text-sm tracking-tight">Pustakam<span className="text-white/40">AI</span></span>
                </div>

                {/* Navigation Tabs - Centered */}
                <nav className="pointer-events-auto flex items-center p-1 bg-white/5 rounded-full border border-white/5 backdrop-blur-md overflow-x-auto max-w-[90vw] scrollbar-hide">
                    {[
                        { id: 'home', label: 'Home' },
                        { id: 'process', label: 'How it Works' },
                        { id: 'street', label: 'Street Mode' },
                        { id: 'stellar', label: 'Stellar Mode' },
                        { id: 'demo', label: 'Demo' },
                        { id: 'features', label: 'Use Cases' }
                    ].map((tab) => (
                        <button
                            key={tab.id}
                            onClick={() => setActiveTab(tab.id as any)}
                            className={`px-4 md:px-5 py-1.5 rounded-full text-[10px] md:text-[11px] font-medium tracking-widest uppercase transition-all duration-300 whitespace-nowrap ${activeTab === tab.id
                                    ? 'bg-white/10 text-white shadow-lg'
                                    : 'text-white/40 hover:text-white/70'
                                }`}
                        >
                            {tab.label}
                        </button>
                    ))}
                </nav>

                {/* Right Actions */}
                <div className="pointer-events-auto flex items-center gap-4 hidden md:flex">
                    <button onClick={onLogin} className="text-[11px] font-medium tracking-wide opacity-50 hover:opacity-100 transition-opacity uppercase">Login</button>
                    <button
                        onClick={onGetStarted}
                        className="bg-white text-black px-5 py-2 rounded-full text-[11px] font-bold tracking-widest uppercase hover:bg-white/90 transition-all shadow-[0_0_20px_rgba(255,255,255,0.2)]"
                    >
                        Try Pustakam
                    </button>
                </div>
            </header>

            {/* Main Content Area */}
            <main className="flex-1 flex flex-col relative z-10 pt-24 pb-20 overflow-hidden">
                {renderContent()}
            </main>

            {/* Fixed Footer */}
            <footer className="absolute bottom-0 left-0 right-0 z-50 px-6 py-4 border-t border-white/5 bg-black/80 backdrop-blur-md">
                <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-3">
                    <div className="flex items-center gap-6 text-[10px] font-medium tracking-wider text-white/30 uppercase">
                        <span>© {new Date().getFullYear()} PustakamAI</span>
                        <span className="hidden md:inline">•</span>
                        <span>Made by Tanmay</span>
                    </div>

                    <div className="flex items-center gap-6">
                        {/* Socials */}
                        <div className="flex items-center gap-4">
                            <a href="https://x.com/404NotTelling" target="_blank" rel="noopener noreferrer" className="text-white/30 hover:text-white transition-colors">
                                <Twitter size={12} />
                            </a>
                            <a href="https://github.com/tanmay-kalbande" target="_blank" rel="noopener noreferrer" className="text-white/30 hover:text-white transition-colors">
                                <Github size={12} />
                            </a>
                            <a href="https://linkedin.com/in/tanmay-kalbande" target="_blank" rel="noopener noreferrer" className="text-white/30 hover:text-white transition-colors">
                                <Linkedin size={12} />
                            </a>
                        </div>

                        <div className="h-3 w-px bg-white/10 hidden md:block" />

                        {/* Links */}
                        <div className="flex items-center gap-4">
                            <button onClick={onShowAbout} className="text-[10px] font-medium tracking-wider text-white/30 hover:text-white uppercase transition-colors">About</button>
                            <button onClick={onShowPrivacy} className="text-[10px] font-medium tracking-wider text-white/30 hover:text-white uppercase transition-colors">Privacy</button>
                            <button onClick={onShowTerms} className="text-[10px] font-medium tracking-wider text-white/30 hover:text-white uppercase transition-colors">Terms</button>
                        </div>
                    </div>
                </div>
            </footer>

        </div>
    );
};

export default LandingPage;