import React, { useState, useEffect, useRef } from 'react';
import { Zap, Binary, Cpu, HardDriveDownload, ChevronRight, MoveRight, Send, X, Github, Twitter, BookOpen, Linkedin, Book, Flame, Atom } from 'lucide-react';
import NebulaBackground from './NebulaBackground';

interface LandingPageProps {
    onLogin: () => void;
    onGetStarted: () => void;
    onShowAbout?: () => void;
    onShowTerms?: () => void;
    onShowPrivacy?: () => void;
}

const DEMO_BOOKS = [
    {
        id: 'street',
        input: 'Stop Overthinking & Take Action',
        title: '"Burn the Boat: No More \'Someday\' Shit"',
        shortTitle: 'Burn the Boat',
        subtitle: "No More 'Someday' Shit",
        desc: 'A raw, aggressive take on crushing debt and stacking assets. Generated by Street Mode AI.',
        mode: 'Street Mode',
        engineDesc: 'High-energy, direct, and action-oriented. Perfect for motivation and rapid consumption.',
        words: '19,914',
        chapters: '10',
        url: 'https://cdn.jsdelivr.net/gh/tanmay-kalbande/pustakam-cdn@main/demo-books/Burn_The_Boat_No_More_Someday_Shit.pdf',
        gradient: 'from-cyan-900/40 to-blue-900/40',
        chapterList: ['Burn the Boat', 'Overthinking is Cancer', 'Fear as a Compass', 'The Cost of Delay']
    },
    {
        id: 'stellar',
        input: 'Personal Finance for Young Adults',
        title: '"Architecting Wealth: A Scientific Framework for Financial Growth"',
        shortTitle: 'Wealth Design',
        subtitle: 'Foundations & Mastery',
        desc: 'A structured, formal guide to financial systems and long-term equity. Generated by Stellar Mode AI.',
        mode: 'Stellar Mode',
        engineDesc: 'Academic, thorough, and highly structured. Ideal for complex topics and deep learning.',
        words: '24,152',
        chapters: '12',
        url: 'https://cdn.jsdelivr.net/gh/tanmay-kalbande/pustakam-cdn@main/demo-books/Foundations_Of_Personal_Finance.pdf',
        gradient: 'from-purple-900/40 to-indigo-900/40',
        chapterList: ['The Hidden Tax', 'Compound Mastery', 'Asset Allocation', 'The Wealth Flywheel']
    }
];

const SpotlightCard = ({ color, step, title, desc, icon: Icon, idx }: any) => {
    const [position, setPosition] = useState({ x: 0, y: 0 });
    const [opacity, setOpacity] = useState(0);
    const cardRef = useRef<HTMLDivElement>(null);

    const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
        if (!cardRef.current) return;

        const rect = cardRef.current.getBoundingClientRect();
        setPosition({
            x: e.clientX - rect.left,
            y: e.clientY - rect.top,
        });
    };

    const handleMouseEnter = () => setOpacity(1);
    const handleMouseLeave = () => setOpacity(0);

    return (
        <div key={idx} className="relative group font-sans">
            {/* Minimal Step Indicator - reduced margin */}
            <div className="flex justify-center mb-2">
                <div className={`w-9 h-9 rounded-full bg-white/[0.02] border border-white/[0.08] flex items-center justify-center text-[10px] font-mono text-${color}-400/60 backdrop-blur-sm group-hover:border-${color}-500/40 transition-colors duration-500`}>
                    {step}
                </div>
            </div>

            {/* Premium Card Content with Spotlight - centered and balanced */}
            <div
                ref={cardRef}
                onMouseMove={handleMouseMove}
                onMouseEnter={handleMouseEnter}
                onMouseLeave={handleMouseLeave}
                className="relative bg-[#050505]/60 border border-white/10 rounded-[22px] px-6 py-8 flex flex-col items-center justify-center text-center hover:border-white/20 transition-all duration-700 min-h-[220px] lg:h-full overflow-hidden"
            >
                <div
                    className="pointer-events-none absolute -inset-px transition-opacity duration-300"
                    style={{
                        opacity,
                        background: `radial-gradient(600px circle at ${position.x}px ${position.y}px, rgba(255,255,255,0.06), transparent 40%)`,
                    }}
                />

                <div className={`w-11 h-11 rounded-xl bg-${color}-500/[0.03] border border-${color}-500/10 flex items-center justify-center mb-5 group-hover:scale-110 transition-transform duration-500 shadow-[0_0_20px_rgba(0,0,0,0.3)] relative z-10`}>
                    <Icon className={`w-5 h-5 text-${color}-400/80`} strokeWidth={1.5} />
                </div>

                <h3 className="text-white font-sans font-medium text-[13px] mb-2.5 tracking-widest uppercase opacity-90 relative z-10">{title}</h3>
                <p className="text-white/25 font-sans text-[11px] leading-relaxed font-light px-1 relative z-10">
                    {desc}
                </p>
                {/* Minimal Connecting Arrow - Centered and Visible */}
                {idx < 3 && (
                    <div className="hidden lg:block absolute -right-6 top-1/2 -translate-y-1/2 z-20 opacity-50 group-hover:opacity-100 group-hover:translate-x-1 transition-all duration-500">
                        <ChevronRight className={`w-6 h-6 text-${color}-400/50 group-hover:text-white drop-shadow-[0_0_5px_rgba(255,255,255,0.2)]`} strokeWidth={2.5} />
                    </div>
                )}
            </div>
        </div>
    );
};

const LandingPage = ({ onLogin, onGetStarted, onShowAbout, onShowTerms, onShowPrivacy }: LandingPageProps) => {
    const [scrolled, setScrolled] = useState(false);
    const [showPromo, setShowPromo] = useState(true);
    const [message, setMessage] = useState('');
    const [messageSent, setMessageSent] = useState(false);
    const [activeDemoIdx, setActiveDemoIdx] = useState(0);
    const activeBook = DEMO_BOOKS[activeDemoIdx];

    useEffect(() => {
        const handleScroll = () => setScrolled(window.scrollY > 20);
        window.addEventListener('scroll', handleScroll);

        const promoDismissed = localStorage.getItem('promo_dismissed');
        if (promoDismissed) {
            setShowPromo(false);
        }

        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    const handleDismissPromo = () => {
        setShowPromo(false);
        localStorage.setItem('promo_dismissed', 'true');
    };

    const handleSendMessage = () => {
        if (!message.trim()) return;

        const subject = encodeURIComponent('Message from PustakamAI Landing Page');
        const body = encodeURIComponent(message);
        window.location.href = `mailto:hello@tanmaysk.in?subject=${subject}&body=${body}`;

        setMessageSent(true);
        setTimeout(() => {
            setMessage('');
            setMessageSent(false);
        }, 3000);
    };

    return (
        <div className="min-h-screen bg-black text-white selection:bg-white/20 selection:text-white overflow-x-hidden font-sans">
            <NebulaBackground />

            {showPromo && (
                <div className="fixed top-24 right-6 z-50 animate-in slide-in-from-right fade-in duration-500">
                    <div className="flex items-center gap-3 pl-4 pr-10 py-3 bg-cyan-950/40 backdrop-blur-md border border-cyan-500/20 rounded-xl shadow-2xl relative group">
                        <span className="relative flex h-2 w-2">
                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-cyan-400 opacity-75"></span>
                            <span className="relative inline-flex rounded-full h-2 w-2 bg-cyan-500"></span>
                        </span>
                        <div className="flex flex-col">
                            <span className="text-cyan-400 text-xs font-bold tracking-wider uppercase">Limited Offer</span>
                            <span className="text-white text-xs font-medium">1 Year Free Membership</span>
                        </div>
                        <button
                            onClick={handleDismissPromo}
                            className="absolute top-2 right-2 p-1 text-white/20 hover:text-white/80 hover:bg-white/10 rounded-full transition-all"
                        >
                            <X size={12} />
                        </button>
                    </div>
                </div>
            )}

            <header className={`fixed top-0 left-0 right-0 z-50 transition-all duration-500 px-6 py-4 ${scrolled ? 'bg-black/95 backdrop-blur-xl border-b border-white/5' : 'bg-gradient-to-b from-black from-40% via-black/80 via-70% to-transparent'}`}>
                <nav className="max-w-7xl mx-auto flex items-center justify-between">
                    <div className="flex items-center gap-8">
                        <div className="flex items-center gap-2 cursor-pointer group" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>
                            <img src="/white-logo.png" alt="Pustakam AI Logo" className="w-6 h-6 opacity-90" />
                            <span className="text-white/90 font-semibold text-sm tracking-tight">Pustakam<span className="text-white/40">AI</span></span>
                        </div>
                        <div className="hidden md:flex items-center gap-8">
                            <button onClick={() => document.getElementById('engines')?.scrollIntoView({ behavior: 'smooth' })} className="text-[13px] font-medium tracking-wide opacity-50 hover:opacity-100 transition-opacity uppercase">
                                The Core Engines
                            </button>
                        </div>
                    </div>

                    <div className="flex items-center gap-6">
                        <button onClick={onLogin} className="text-[13px] font-medium tracking-wide opacity-50 hover:opacity-100 transition-opacity uppercase hidden sm:block">Login</button>
                        <button
                            onClick={onGetStarted}
                            className="border border-white/10 px-6 py-2 rounded-full text-[12px] font-medium tracking-widest uppercase hover:bg-gradient-to-br hover:from-cyan-500/10 hover:to-blue-500/10 hover:border-cyan-500/20 transition-all duration-500"
                        >
                            Try Pustakam
                        </button>
                    </div>
                </nav>
            </header>

            <main className="relative z-[2] flex flex-col items-center justify-center min-h-screen px-6 text-center">
                <div className="relative z-10 max-w-4xl mb-6">
                    <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold tracking-tight leading-[1.1] text-white">
                        Your Infinite
                        <span className="block text-white/60">Knowledge Engine</span>
                    </h1>
                </div>

                <button
                    onClick={onGetStarted}
                    className="relative z-10 px-8 py-3.5 bg-white/5 hover:bg-white/10 border border-white/10 hover:border-white/20 rounded-full text-sm font-medium tracking-wide text-white/90 hover:text-white transition-all group flex items-center gap-2"
                >
                    <span>Start Learning Now</span>
                    <MoveRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                </button>

                <div className="absolute bottom-8 left-8 flex flex-col items-center gap-2 opacity-40 hover:opacity-100 transition-opacity cursor-pointer" onClick={() => window.scrollTo({ top: window.innerHeight, behavior: 'smooth' })}>
                    <div className="w-4 h-4 border-b border-l border-white/50 rotate-[-45deg]" />
                </div>
            </main>

            <section id="features" className="relative z-[3] pt-8 pb-12 px-4 md:px-6">
                <div className="absolute inset-x-0 h-40 bg-gradient-to-b from-transparent via-black/30 to-black/50 pointer-events-none" style={{ top: '-160px' }} />
                <div className="absolute inset-0 bg-black/50" style={{ zIndex: -1 }} />
                <div className="max-w-7xl mx-auto mb-10">
                    <div className="text-center mb-10 font-sans">
                        <span className="text-[10px] tracking-[0.4em] uppercase text-cyan-400 mb-4 block opacity-80 font-sans">The Process</span>
                        <h2 className="text-4xl font-medium tracking-tight text-white mb-3 font-sans">Your Learning Journey</h2>
                        <p className="text-white/20 text-[12px] tracking-widest font-normal font-sans">From vision to ethereal archive in four neural steps</p>
                    </div>

                    <div className="relative max-w-5xl mx-auto px-4 mb-20">
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 md:gap-6">
                            {[
                                {
                                    step: '01',
                                    title: 'Initialize Vision',
                                    desc: 'Seed your core concept into the knowledge engine',
                                    icon: Zap,
                                    color: 'cyan'
                                },
                                {
                                    step: '02',
                                    title: 'Neural Mapping',
                                    desc: 'Architect the tone, depth and learning logic',
                                    icon: Binary,
                                    color: 'purple'
                                },
                                {
                                    step: '03',
                                    title: 'Engine Synthesis',
                                    desc: 'AI orchestration begins building your knowledge base',
                                    icon: Cpu,
                                    color: 'amber'
                                },
                                {
                                    step: '04',
                                    title: 'Ethereal Export',
                                    desc: 'Extract your high-fidelity instant PDF book',
                                    icon: HardDriveDownload,
                                    color: 'emerald'
                                }
                            ].map((item, idx) => (
                                <SpotlightCard key={idx} {...item} idx={idx} />
                            ))}
                        </div>

                        {/* Redesigned Security Indicator - Technical & Minimal */}
                        <div className="mt-14 flex justify-center opacity-30">
                            <div className="flex items-center gap-4">
                                <div className="h-px w-8 bg-gradient-to-r from-transparent to-white/20" />
                                <span className="text-[9px] uppercase tracking-[0.5em] font-light text-white/50 font-sans">
                                    Encrypted Core • Secure Neural Channels • TLS 1.3
                                </span>
                                <div className="h-px w-8 bg-gradient-to-l from-transparent to-white/20" />
                            </div>
                        </div>

                        <div className="text-center mt-10">
                            <button onClick={onGetStarted} className="inline-flex items-center gap-4 text-[10px] font-medium tracking-[0.4em] uppercase text-white/10 hover:text-cyan-400 transition-all duration-700 group font-sans">
                                Initialize Engine
                                <MoveRight className="w-3.5 h-3.5 group-hover:translate-x-2 transition-transform duration-700" />
                            </button>
                        </div>
                    </div>
                </div>

                <div className="max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                    {[
                        { title: 'Instant Generation', desc: 'Get complete learning guides in seconds. Just describe what you want.', icon: Zap, color: 'cyan' },
                        { title: 'Structured Content', desc: 'Every book includes chapters, modules, quizzes, and progress tracking.', icon: Book, color: 'purple' },
                        { title: 'Learn Anything', desc: 'From programming to philosophy — if you can describe it, Pustakam can teach it.', icon: BookOpen, color: 'emerald' }
                    ].map((item, i) => (
                        <div key={i} className="group relative p-8 rounded-3xl bg-white/[0.02] border border-white/5 hover:border-white/10 transition-all duration-500 hover:bg-white/[0.04] overflow-hidden">
                            <div className={`absolute top-0 right-0 p-8 opacity-0 group-hover:opacity-10 transition-opacity duration-500 text-${item.color}-400 transform translate-x-4 -translate-y-4 group-hover:translate-x-2 group-hover:-translate-y-2`}>
                                <item.icon className="w-24 h-24" />
                            </div>
                            <div className={`w-10 h-10 rounded-xl bg-${item.color}-500/10 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-500 border border-${item.color}-500/20`}>
                                <item.icon className={`w-5 h-5 text-${item.color}-400`} strokeWidth={1.5} />
                            </div>
                            <h3 className="text-lg font-medium mb-3 text-white/90 group-hover:text-white transition-colors relative z-10">{item.title}</h3>
                            <p className="text-white/30 font-light leading-relaxed text-sm relative z-10 group-hover:text-white/50 transition-colors">{item.desc}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Dual Engine Showcase Section */}
            <section id="engines" className="relative z-[3] py-20 px-4 md:px-6 overflow-hidden">
                <div className="absolute inset-x-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent top-0" />
                <div className="absolute inset-0 bg-black/50" style={{ zIndex: -1 }} />
                <div className="absolute inset-x-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent bottom-0" />

                <div className="max-w-5xl mx-auto">
                    <div className="text-center mb-12">
                        <span className="text-[10px] tracking-[0.4em] uppercase text-white/40 mb-3 block font-sans">The Core Engines</span>
                        <h2 className="text-3xl md:text-4xl font-medium tracking-tight text-white mb-4 font-sans">Two Paths to Knowledge</h2>
                        <p className="text-white/30 text-sm max-w-xl mx-auto leading-relaxed">
                            Select the neural architecture that matches your learning style. Pustakam adapts its generation engine to your needs.
                        </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-8 relative">
                        {/* Styles for the glowing divider effect */}
                        <div className="hidden md:block absolute left-1/2 top-0 bottom-0 w-px bg-white/5 -translate-x-1/2 z-0">
                            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 rounded-full bg-black border border-white/10 flex items-center justify-center text-[10px] font-bold text-white/20 z-10 font-mono">VS</div>
                        </div>

                        {/* Street Mode Card */}
                        <div className="group relative bg-[#050505] border border-white/5 hover:border-white/10 rounded-2xl p-8 transition-all duration-500 overflow-hidden hover:bg-white/[0.01]">
                            <div className="relative z-10 flex flex-col h-full">
                                <div className="flex items-center justify-between mb-6">
                                    <div className="w-12 h-12 rounded-xl bg-white/[0.02] border border-white/5 flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
                                        <Flame className="w-6 h-6 text-cyan-400 transition-all duration-300 group-hover:animate-pulse" strokeWidth={1.5} />
                                    </div>
                                    <span className="px-3 py-1 rounded-full bg-cyan-950/20 border border-cyan-500/20 text-[10px] uppercase tracking-wider text-cyan-400 font-medium">
                                        Action Oriented
                                    </span>
                                </div>

                                <h3 className="text-2xl font-medium text-white mb-2 font-sans">Street Mode</h3>
                                <p className="text-white/40 text-sm mb-6 leading-relaxed">
                                    Raw, direct, and aggressive. Cuts through the noise to give you actionable steps. Best for motivation and "how-to" guides.
                                </p>

                                <div className="mt-auto space-y-3">
                                    {['Direct "No-BS" Tone', 'Focus on Execution', 'High Energy Delivery'].map((feature, i) => (
                                        <div key={i} className="flex items-center gap-3 text-xs text-white/60">
                                            <div className="w-1 h-1 rounded-full bg-cyan-500/50" />
                                            {feature}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>

                        {/* Stellar Mode Card */}
                        <div className="group relative bg-[#050505] border border-white/5 hover:border-white/10 rounded-2xl p-8 transition-all duration-500 overflow-hidden hover:bg-white/[0.01]">
                            <div className="relative z-10 flex flex-col h-full">
                                <div className="flex items-center justify-between mb-6">
                                    <div className="w-12 h-12 rounded-xl bg-white/[0.02] border border-white/5 flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
                                        <Atom className="w-6 h-6 text-purple-400 group-hover:animate-[spin_4s_linear_infinite]" strokeWidth={1.5} />
                                    </div>
                                    <span className="px-3 py-1 rounded-full bg-purple-950/20 border border-purple-500/20 text-[10px] uppercase tracking-wider text-purple-400 font-medium">
                                        Deep Learning
                                    </span>
                                </div>

                                <h3 className="text-2xl font-medium text-white mb-2 font-sans">Stellar Mode</h3>
                                <p className="text-white/40 text-sm mb-6 leading-relaxed">
                                    Academic, structured, and thorough. Builds a complete mental model with theory and examples. Best for deep understanding.
                                </p>

                                <div className="mt-auto space-y-3">
                                    {['Academic Structure', 'Theory & Concept Mastery', 'Comprehensive Coverage'].map((feature, i) => (
                                        <div key={i} className="flex items-center gap-3 text-xs text-white/60">
                                            <div className="w-1 h-1 rounded-full bg-purple-500/50" />
                                            {feature}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* See Pustakam in Action Section */}
            <section className="relative z-[3] pt-8 pb-12 px-4 md:px-6">
                <div className="absolute inset-0 bg-black/50" style={{ zIndex: -1 }} />
                <div className="max-w-7xl mx-auto">
                    {/* Two Column Layout */}
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">

                        {/* Left Side - Title & CTA */}
                        <div className="font-sans">
                            <span className={`text-[10px] tracking-[0.4em] uppercase mb-4 block font-sans ${activeDemoIdx === 0 ? 'text-cyan-400' : 'text-purple-400'}`}>Live Demo</span>
                            <h2 className="text-4xl lg:text-5xl font-medium tracking-tight text-white mb-4 font-sans leading-tight">See Pustakam<br />in Action</h2>
                            <p className="text-white/30 text-sm mb-6 max-w-md leading-relaxed">Experience the raw power of AI-generated books. Download this sample and see what Pustakam can create for you.</p>

                            {/* Topic Input Display */}
                            <div className="mb-8">
                                <div className="relative">
                                    <div className="relative bg-[#050505]/80 border border-white/10 rounded-xl p-4">
                                        <div className="flex items-center justify-between mb-2">
                                            <div className="flex items-center gap-3">
                                                <div className={`w-2 h-2 rounded-full ${activeDemoIdx === 0 ? 'bg-cyan-400' : 'bg-purple-400'}`} />
                                                <span className="text-[10px] uppercase tracking-widest text-white/40 font-mono">Topic Selection</span>
                                            </div>
                                            <div className="flex bg-white/5 p-1 rounded-xl border border-white/5 overflow-hidden">
                                                {DEMO_BOOKS.map((book, i) => (
                                                    <button
                                                        key={i}
                                                        onClick={() => setActiveDemoIdx(i)}
                                                        className={`relative px-3 py-1.5 rounded-lg text-[9px] font-bold uppercase tracking-widest transition-all duration-500 flex items-center gap-2 ${i === activeDemoIdx
                                                            ? 'text-white bg-white/10 shadow-[0_0_15px_rgba(255,255,255,0.05)]'
                                                            : 'text-white/30 hover:text-white/60'
                                                            }`}
                                                    >
                                                        {i === 0 ? <Flame className={`w-3 h-3 ${i === activeDemoIdx ? 'text-cyan-400' : 'text-white/20'}`} /> : <Atom className={`w-3 h-3 ${i === activeDemoIdx ? 'text-purple-400' : 'text-white/20'}`} />}
                                                        <span>{book.mode.split(' ')[0]}</span>
                                                        {i === activeDemoIdx && (
                                                            <div className={`absolute bottom-0 left-1 right-1 h-[1px] bg-gradient-to-r from-transparent ${i === 0 ? 'via-cyan-400' : 'via-purple-400'} to-transparent`} />
                                                        )}
                                                    </button>
                                                ))}
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-2 mb-2">
                                            <span className="text-[10px] text-white/30 font-mono">EMULATING INPUT:</span>
                                            <span className={`text-[10px] font-mono font-medium animate-pulse tracking-tight ${activeDemoIdx === 0 ? 'text-cyan-400' : 'text-purple-400'}`}>"{activeBook.input}"</span>
                                        </div>
                                        <p className="text-white/90 text-sm md:text-base font-medium h-12 md:h-10 leading-snug">
                                            {activeBook.title}
                                        </p>
                                        <div className="flex items-center gap-4 mt-3 text-[11px] text-white/30">
                                            <span className="flex items-center gap-1.5">
                                                <span className={`${activeDemoIdx === 0 ? 'text-cyan-400/50' : 'text-purple-400/50'}`}>●</span> {activeBook.mode}
                                            </span>
                                            <span>{activeBook.words}</span>
                                            <span>{activeBook.chapters}</span>
                                        </div>
                                    </div>

                                    {/* Engine Spotlight Explanation */}
                                    <div className={`mt-4 p-4 rounded-xl border transition-all duration-700 ${activeDemoIdx === 0
                                        ? 'bg-cyan-500/[0.03] border-cyan-500/10'
                                        : 'bg-purple-500/[0.03] border-purple-500/10'
                                        }`}>
                                        <div className="flex items-start gap-3">
                                            <div className={`mt-0.5 p-1.5 rounded-lg border flex-shrink-0 ${activeDemoIdx === 0
                                                ? 'bg-cyan-500/10 border-cyan-500/20 text-cyan-400'
                                                : 'bg-purple-500/10 border-purple-500/20 text-purple-400'
                                                }`}>
                                                {activeDemoIdx === 0 ? <Flame className="w-3 h-3" /> : <Atom className="w-3 h-3" />}
                                            </div>
                                            <div>
                                                <h4 className={`text-[10px] uppercase tracking-widest font-bold mb-1 ${activeDemoIdx === 0 ? 'text-cyan-400' : 'text-purple-400'
                                                    }`}>
                                                    {activeBook.mode} Characteristics
                                                </h4>
                                                <p className="text-[11px] text-white/40 leading-relaxed italic">
                                                    {activeBook.engineDesc}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* CTA Button - Back on Left & Squarish */}
                            <button
                                onClick={onGetStarted}
                                className="inline-flex items-center gap-3 px-8 py-3.5 bg-white/5 hover:bg-gradient-to-br hover:from-cyan-500/10 hover:to-blue-500/10 border border-white/10 hover:border-cyan-500/20 rounded-xl text-sm font-medium tracking-wide text-white/90 hover:text-white transition-all duration-500 group"
                            >
                                <span>Create Your Own Book</span>
                                <MoveRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                            </button>
                        </div>

                        {/* Right Side - Book Preview Card */}
                        <div className="relative group">
                            <div className="relative bg-[#050505]/60 border border-white/10 rounded-2xl overflow-hidden group-hover:border-white/20 transition-all duration-500">
                                {/* Book Header */}
                                <div className="relative p-6">
                                    <div className="flex items-center gap-2 mb-4">
                                        <span className="px-2 py-1 rounded-full bg-white/5 border border-white/10 text-[10px] uppercase tracking-wider text-white/50 font-medium">Street Mode</span>
                                        <span className="px-2 py-1 rounded-full bg-white/5 border border-white/10 text-[10px] uppercase tracking-wider text-white/50 font-medium">PDF Ready</span>
                                    </div>

                                    <div className="flex items-start gap-5">
                                        {/* Book Cover Mockup - Solid PDF/Book Theme */}
                                        <div className="relative flex-shrink-0 w-24 h-32 bg-[#0a0a0f] rounded-lg border border-cyan-500/30 shadow-2xl shadow-cyan-500/10 transform group-hover:rotate-[-2deg] group-hover:scale-105 transition-all duration-500 overflow-hidden">
                                            {/* Opaque Gradient Backing */}
                                            <div className={`absolute inset-0 bg-gradient-to-br ${activeBook.gradient} opacity-100 transition-all duration-700`} />

                                            {/* Page Stack Effect (Right Edge) */}
                                            <div className="absolute top-1 bottom-1 right-[2px] w-[1px] bg-white/10" />
                                            <div className="absolute top-2 bottom-2 right-[4px] w-[1px] bg-white/5" />

                                            <div className="relative inset-0 flex flex-col items-center justify-center p-3 text-center h-full">
                                                <div className="w-9 h-9 mb-3 bg-gradient-to-br from-cyan-500/20 to-blue-500/20 rounded-lg flex items-center justify-center border border-white/10 group-hover:scale-110 transition-transform duration-500">
                                                    {activeDemoIdx === 0 ? <Flame className="w-4 h-4 text-cyan-400 group-hover:animate-pulse" /> : <Atom className="w-4 h-4 text-purple-400 group-hover:animate-[spin_4s_linear_infinite]" />}
                                                </div>
                                                <h4 className="text-white text-[10px] font-bold leading-tight">{activeBook.shortTitle}</h4>
                                                <p className="text-white/50 text-[8px] mt-0.5 whitespace-nowrap">{activeBook.subtitle}</p>
                                            </div>
                                            <div className="absolute bottom-1.5 left-0 right-0 text-center">
                                                <span className="text-[7px] text-white/30 uppercase tracking-wider">PustakamAI</span>
                                            </div>
                                        </div>

                                        {/* Book Info */}
                                        <div className="flex-1">
                                            <h3 className="text-lg font-bold text-white mb-1.5 leading-tight">{activeBook.title.replace(/"/g, '')}</h3>
                                            <p className="text-white/40 text-xs mb-3 leading-relaxed">{activeBook.desc}</p>

                                            <div className="flex flex-wrap gap-2">
                                                <div className="px-2.5 py-1 bg-white/5 rounded-lg">
                                                    <span className="text-white/50 text-[9px] block">Words</span>
                                                    <span className="text-white font-medium text-xs">{activeBook.words}</span>
                                                </div>
                                                <div className="px-2.5 py-1 bg-white/5 rounded-lg">
                                                    <span className="text-white/50 text-[9px] block">Chapters</span>
                                                    <span className="text-white font-medium text-xs">{activeBook.chapters}</span>
                                                </div>
                                                <div className="px-2.5 py-1 bg-white/5 rounded-lg">
                                                    <span className="text-white/50 text-[9px] block">Provider</span>
                                                    <span className="text-white font-medium text-xs">Cerebras</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {/* Chapter Preview */}
                                <div className="px-6 py-3 border-t border-white/5">
                                    <p className="text-[9px] uppercase tracking-widest text-white/30 mb-2">Chapters Include</p>
                                    <div className="grid grid-cols-2 gap-1.5 text-xs text-white/50">
                                        {activeBook.chapterList.map((ch, idx) => (
                                            <span key={idx}>→ {ch}</span>
                                        ))}
                                    </div>
                                </div>

                                {/* Download Section */}
                                <div className="p-5 border-t border-white/5">
                                    <div className="flex items-center justify-between gap-4">
                                        <div>
                                            <p className="text-white/60 text-sm font-medium">Ready to see it?</p>
                                            <p className="text-white/30 text-xs">Download the full {activeBook.words} word PDF</p>
                                        </div>
                                        <a
                                            href={activeBook.url}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className={`group/btn flex items-center gap-2 px-5 py-2.5 bg-white/5 border border-white/10 rounded-full text-white/90 hover:text-white text-sm font-medium transition-all duration-500 hover:shadow-[0_0_20px_rgba(255,255,255,0.05)] ${activeDemoIdx === 0
                                                ? 'hover:border-cyan-500/20 hover:bg-gradient-to-br hover:from-cyan-500/10 hover:to-blue-500/10'
                                                : 'hover:border-purple-500/20 hover:bg-gradient-to-br hover:from-purple-500/10 hover:to-indigo-500/10'
                                                }`}
                                        >
                                            <HardDriveDownload className={`w-4 h-4 ${activeDemoIdx === 0 ? 'text-cyan-400' : 'text-purple-400'}`} />
                                            <span>Download PDF</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <div className="relative z-[3] h-20 bg-gradient-to-b from-black/50 to-black pointer-events-none" />

            <footer className="relative z-[3] pt-8 pb-6 px-4 md:px-6 bg-black">
                <div className="max-w-7xl mx-auto">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-10 pb-8 border-b border-white/5">
                        <div className="md:col-span-1">
                            <div className="flex items-center gap-2 mb-4 cursor-pointer" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>
                                <img src="/white-logo.png" alt="Pustakam AI Logo" className="w-6 h-6" />
                                <span className="text-white font-semibold">PustakamAI</span>
                            </div>
                            <p className="text-white/40 text-sm leading-relaxed mb-4">
                                Your infinite knowledge engine. Generate personalized learning guides with AI.
                            </p>

                            <div className="flex gap-3">
                                <a href="https://x.com/404NotTelling" target="_blank" rel="noopener noreferrer" className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center hover:bg-white/10 transition-colors">
                                    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" className="text-white/60">
                                        <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                                    </svg>
                                </a>
                                <a href="https://github.com/tanmay-kalbande" target="_blank" rel="noopener noreferrer" className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center hover:bg-white/10 transition-colors">
                                    <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor" className="text-white/60">
                                        <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                                    </svg>
                                </a>
                                <a href="https://linkedin.com/in/tanmay-kalbande" target="_blank" rel="noopener noreferrer" className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center hover:bg-white/10 transition-colors">
                                    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" className="text-white/60">
                                        <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                                    </svg>
                                </a>
                            </div>
                        </div>

                        <div>
                            <h4 className="text-white/80 font-medium text-sm mb-4">Product</h4>
                            <ul className="space-y-2">
                                <li><button onClick={onGetStarted} className="text-white/40 text-sm hover:text-white transition-colors">Get Started</button></li>
                                <li><button onClick={() => document.getElementById('features')?.scrollIntoView({ behavior: 'smooth' })} className="text-white/40 text-sm hover:text-white transition-colors">Features</button></li>
                                <li><span className="text-cyan-400 text-sm">1 Year Free ✨</span></li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-white/80 font-medium text-sm mb-4">Company</h4>
                            <ul className="space-y-2">
                                <li><button onClick={onShowAbout} className="text-white/40 text-sm hover:text-white transition-colors">About</button></li>
                                <li><a href="mailto:hello@tanmaysk.in" className="text-white/40 text-sm hover:text-white transition-colors">Contact</a></li>
                                <li><button onClick={onShowTerms} className="text-white/40 text-sm hover:text-white transition-colors">Terms of Service</button></li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-white/80 font-medium text-sm mb-4">Message the Creator</h4>
                            <div className="relative">
                                <textarea
                                    value={message}
                                    onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setMessage(e.target.value)}
                                    placeholder="Share your thoughts, feedback, or ideas..."
                                    className="w-full px-4 py-3 pb-10 bg-white/5 border border-white/10 rounded-lg text-white/90 text-sm placeholder:text-white/30 focus:outline-none focus:border-white/30 focus:bg-white/[0.07] transition-all resize-none h-24"
                                    maxLength={500}
                                />
                                {message.length > 0 && (
                                    <span className="absolute bottom-3 left-4 text-[10px] text-white/20">
                                        {message.length}/500
                                    </span>
                                )}
                                <button
                                    onClick={handleSendMessage}
                                    disabled={!message.trim() || messageSent}
                                    className="absolute bottom-3 right-3 px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/10 hover:border-white/20 rounded-md text-white/80 text-xs font-medium transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1.5 group"
                                >
                                    {messageSent ? (
                                        <>
                                            <span className="text-green-400">✓ Sent</span>
                                        </>
                                    ) : (
                                        <>
                                            <Send className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" />
                                            <span>Send</span>
                                        </>
                                    )}
                                </button>
                            </div>
                        </div>
                    </div>

                    <div className="flex flex-col md:flex-row justify-between items-center gap-4 pt-6">
                        <p className="text-white/30 text-xs">© {new Date().getFullYear()} PustakamAI • Made by Tanmay</p>
                        <div className="flex items-center gap-6">
                            <button onClick={onShowPrivacy} className="text-white/30 text-xs hover:text-white transition-colors">Privacy</button>
                            <button onClick={onShowTerms} className="text-white/30 text-xs hover:text-white transition-colors">Terms</button>
                            <button onClick={onLogin} className="text-white/40 text-xs hover:text-white transition-colors">Login</button>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    );
};

export default LandingPage;